openapi: 3.0.1
info:
  title: MyAnimeList Plugin
  description: Plugin for interacting with MyAnimeList; retrieve info about specific anime/manga, access general or seasonal rankings, read forum topics, get or update info about an authenticated user, and more.
  version: "v1"
servers:
  - url: https://chatgpt-mal-plugin-2ce3020b3a58.herokuapp.com
paths:
  /anime/suggestions/{limit}:
    get:
      operationId: getAnimeSuggestions
      summary: Get anime suggestions
      parameters:
        - in: path
          name: limit
          schema:
            type: integer
          required: false
          description: The number of suggestions to return.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getAnimeSuggestionsResponse"
  /anime/season/{year}/{season}/{limit}:
    get:
      operationId: getAnimeSeason
      summary: Get anime from a specific season
      parameters:
        - in: path
          name: year
          schema:
            type: integer
          required: true
          description: The year of the season.
        - in: path
          name: season
          schema:
            type: string
          required: true
          description: The season.
        - in: path
          name: limit
          schema:
            type: integer
          required: false
          description: The number of anime to return.
      responses:
        "200":
          description: OK

components:
  schemas:
    getAnimeSuggestionsResponse:
      type: object
      properties:
        suggestions:
          type: array
          items:
            type: string
          description: The list of suggestions.
    getAnimeSeasonResponse:
      type: object
      properties:
        anime:
          type: array
          items:
            type: string
          description: The list of seasonal anime.
